version: '3'
services:
    nodesail.test:
        build:
            context: ./runtimes/17
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                NPM_AUTH: '${NPM_AUTH}'
        image: nodesail-17/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
            - '${HOST:-"localhost"}:${HOST_IP:-"127.0.0.1"}'
            - '${DB:-"localhost"}:${DB_IP:-"127.0.0.1"}'
        ports:
            - '${APP_PORT:-80}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - './:/code'
            - '${APPS}:/code'
        networks:
            - sail
networks:
    sail:
        driver: bridge
